# test_getBlockByHash.tavern.yaml

---

test_name: This method is used to obtain the block content based on block hash.

includes:
  - !include common.yaml

stages:
  - name: Both CurrentBlockHeight and HeaderHash are changing frequently.
    request:
      url: "{service.proto:s}://{service.host:s}:{service.port:d}"
      json:
        jsonrpc: "2.0"
        method: "seele_getBlockByHash"
        params:
          - "0x000002069d9de64bad509239e2a121afbf7de183576457a1d1fb077d19fa3e8c"
          - true
        id: 1

      method: POST
      headers:
        content-type: application/json

    response:
      status_code: 200
      body:
        jsonrpc: '2.0'
        id: 1
        error:
          code: -32000
          message: "leveldb: not found"
