# test_getBlockHeight.tavern.yaml

---

test_name: This method is used to obtain the height of the blockchain.

includes:
  - !include common.yaml

stages:
  - name: Both CurrentBlockHeight and HeaderHash are changing frequently.
    request:
      url: "{service.proto:s}://{service.host:s}:{service.port:d}"
      json:
        jsonrpc: "2.0"
        method: "seele_getBlockHeight"
        params: "[]"
        id: 1

      method: POST
      headers:
        content-type: application/json

    response:
      status_code: 200
      body:
        jsonrpc: '2.0'
        id: 1
        # result: 1928 # Dynamically
