# test_getBalance.tavern.yaml

---

test_name: This method returns the account balance.

includes:
  - !include common.yaml

stages:
  - name: Invalid wallet address test
    request:
      url: "{service.proto:s}://{service.host:s}:{service.port:d}"
      json:
        jsonrpc: "2.0"
        method: "seele_getBalance"
        params: ["0x4c10f2cd2159bb432094e3be7e17904c2b4aeb21"]
        id: 1

      method: POST
      headers:
        content-type: application/json

    response:
      status_code: 200
      body:
        jsonrpc: '2.0'
        id: 1
        error:
          code: -32602
          message: "missing value for required argument 1"
