# test_addTx.tavern.yaml

---

test_name: This method submits a transaction to the node.

includes:
  - !include common.yaml

stages:
  - name: Both CurrentBlockHeight and HeaderHash are changing frequently.
    request:
      url: "{service.proto:s}://{service.host:s}:{service.port:d}"
      json:
        jsonrpc: "2.0"
        method: "seele_addTx"
        params:
          - Hash: "0xe2648efdfe6eb6a1d4beb2461e2dff3ee9584fb14bc3ae15b38f612c617e12ae"
            Data:
              From: "0x4c10f2cd2159bb432094e3be7e17904c2b4aeb21"
              To: "0x0ea2a45ab5a909c309439b0e004c61b7b2a3e831"
              Amount: 20000
              AccountNonce: 21
              Fee: 1
              Timestamp: 0
              Payload: ""
            Signature:
              Sig: "RnlFViK1RAUs9UB5WCesa6W5f9qmuFvqnM7W+9W1iUwsPIguyUI1S0fm8ysrJ4ZeL/Hx/GFEq5FGn1guvySVPQE="
        id: 1
      method: POST
      headers:
        content-type: application/json


    response:
      status_code: 200
      body:
        jsonrpc: '2.0'
        id: 1
        error:
          code: -32000
          message: "failed to validate object ===> failed to validate tx ===> gas price is nil"
